import { StyleSheet } from 'react-native';
import { colors } from '../styles/globalStyles';

export const styles = StyleSheet.create({
    dateHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.white,
        padding: 20,
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 12,
        gap: 12,
        shadowColor: colors.darkGray,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    dateText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.textDark,
        textTransform: 'capitalize',
    },
    summaryGrid: {
        padding: 16,
        gap: 12,
    },
    summaryCard: {
        padding: 20,
        borderRadius: 16,
        alignItems: 'center',
        shadowColor: colors.darkGray,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    summaryValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.white,
        marginTop: 8,
        marginBottom: 4,
    },
    summaryLabel: {
        fontSize: 14,
        color: colors.white,
        fontWeight: '600',
        opacity: 0.9,
    },
    salesSection: {
        marginTop: 8,
        marginBottom: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginBottom: 12,
    },
    salesCount: {
        color: colors.primaryPink,
        fontWeight: '600',
        fontSize: 14,
    },
    saleCard: {
        backgroundColor: colors.white,
        marginHorizontal: 16,
        marginVertical: 6,
        borderRadius: 12,
        padding: 16,
        shadowColor: colors.darkGray,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    saleHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    productName: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.textDark,
        flex: 1,
    },
    saleTotal: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.primaryFuchsia,
    },
    saleDetails: {
        gap: 6,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    detailText: {
        fontSize: 14,
        color: colors.textLight,
    },
    emptyState: {
        alignItems: 'center',
        padding: 40,
        marginTop: 20,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.textDark,
        marginTop: 16,
    },
    emptySubtext: {
        fontSize: 14,
        color: colors.textLight,
        textAlign: 'center',
        marginTop: 8,
    },
    loadingText: {
        marginTop: 12,
        color: colors.textLight,
    },
    // Nuevos estilos añadidos
    testingWarning: {
        fontSize: 12,
        color: colors.error,
        fontWeight: '600',
        marginTop: 4,
        textAlign: 'center',
    },
    toggleButton: {
        backgroundColor: colors.primaryFuchsia,
        marginHorizontal: 16,
        marginVertical: 8,
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    toggleButtonText: {
        color: colors.white,
        fontWeight: '600',
        fontSize: 14,
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    errorText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.error,
        marginTop: 16,
        textAlign: 'center',
    },
    errorSubtext: {
        fontSize: 14,
        color: colors.textLight,
        textAlign: 'center',
        marginTop: 8,
    },
    retryText: {
        fontSize: 16,
        color: colors.primaryPink,
        fontWeight: '600',
        marginTop: 16,
        textDecorationLine: 'underline',
    },
    totalProductsCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        marginHorizontal: 16,
        marginTop: 8,
        padding: 16,
        borderRadius: 12,
        gap: 12,
        shadowColor: colors.darkGray,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    totalProductsText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.textDark,
    },
    dayTotalCard: {
        backgroundColor: colors.primaryFuchsia,
        marginHorizontal: 16,
        marginTop: 16,
        padding: 20,
        borderRadius: 12,
        alignItems: 'center',
    },
    dayTotalText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.white,
    },
});